version: '3.8'

services:
  db:
    image: postgres:15
    container_name: reservation_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reservation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: cinemax_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:1234@127.0.0.1:5432/reservation_db
    depends_on:
      - db

volumes:
  postgres_data: